### ISSUE TITLE
Specify somehow which modules are necessary to run the demonstration

### ISSUE THREAD

**Issue by DanielGlaas** [NeilGirdhar/glx#1]
I hardly tried to get the demonstration [text.py](https://github.com/NeilGirdhar/glx/blob/master/demonstration/text.py) running, but I always get an import error in line 8
`from geometry import Geometry`
I was not able to figure out which module I need to install. 

I tried `from geometry import Geometry`, but this didn't solve the problem.

I recommend to add this either into the header of this file or into a readme file located in the demonstration folder.

**Comment by NeilGirdhar** [comment]
Hi Daniel, `geometry` is right there in the demonstration directory.  Can you try switching to that directory and then running `python text.py`?  I haven't looked at this repo in years, but it worked when I tested it last.

**Comment by DanielGlaas** [comment]
Hi Neil, many thanks for this quick reply.
Well, this solution was toooo easy ...
I just downloaded only text.py, I expected that it is a standalone file. Now it executes but gives theses errors:

On Raspberry Pi 4:
> QEGLPlatformContext: Failed to create context: 3009
> QOpenGLWidget: Failed to create context
> QEGLPlatformContext: Failed to create context: 3009
> QOpenGLWidget: Failed to create context
> QEGLPlatformContext: Failed to create context: 3009
> composeAndFlush: QOpenGLContext creation failed
> composeAndFlush: makeCurrent()  failed

On Ubuntu 18.04:
> Traceback (most recent call last):
>   File "./text.py", line 36, in initializeGL
>     self.font = Font('/usr/share/fonts/X11/100dpi/timBI14.pcf.gz', 14)
>   File "/home/daniel/.local/lib/python3.6/site-packages/glx/font/font.py", line 42, in __init__
>     self.face.set_char_size(size * 64)
>   File "/home/daniel/.local/lib/python3.6/site-packages/freetype/__init__.py", line 1206, in set_char_size
>     if error: raise FT_Exception( error)
> freetype.ft_errors.FT_Exception: FT_Exception:  (invalid pixel size)
I already change the used font filename from windows representation to unix file. But what is this pixel size thing about?

**Comment by NeilGirdhar** [comment]
Looks like a freetype error.  I'm on Ubuntu 20.04.  I can check it out later.  Or you can try to mess with freetype to get it to work.
